### ISSUE TITLE
Template repos’ README

### ISSUE THREAD

**Issue by p5150j** [AmplicaLabs/gateway#157]
Lets make a template to share between all gateway services repos.
This template will be the outline for all service reposn readmes

**Comment by p5150j** [comment]
<div align="center">
 
  <img src="https://raw.githubusercontent.com/frequency-chain/frequency-xyz/main/src/lib/assets/Logo.svg" alt="logo" width="140"  height="auto" />
  <br/>

  <h3><b>Gateway services  README Template</b></h3>

</div>



# 📗 Table of Contents

- [📖 About the Project](#about-project)
- [🔍 Arch Map](#arch-map)
  - [🛠 Built With](#built-with)
    - [Tech Stack](#tech-stack)
    - [Key Features](#key-features)
  - [🚀 Live OpenAPI Docs](#live-demo)
- [💻 Getting Started](#getting-started)
  - [Prerequisites](#prerequisites)
  - [Setup](#setup)
  - [Install](#install)
  - [Usage](#usage)
  - [Run tests](#run-tests)
  - [Deployment](#deployment)
- [👥 Authors](#authors)
- [🤝 Contributing](#contributing)
- [⭐️ Show your support](#support)
- [🙏 Acknowledgements](#acknowledgements)
- [❓ FAQ (OPTIONAL)](#faq)
- [📝 License](#license)



# 📖 [project_name] <a name="about-project"></a>

> Describe your project in 2 paragraphs.

**[project__name]** is a...



## 🔭  Mermaid Arch maps <a name="arch-map"></a>

> Describe the arch map for the project.

[![](https://mermaid.ink/img/pako:eNpNj0FLxDAQhf9KnJuQLcmmTbo57CIIiuBpb9JLaGdtoU12Y4LW0v9u2io4p8fMe9_MTFC7BkHDB94i2hofO_PuzVBZkuqh72rcHY8vrrWaPGPfO7JoSlr3SYxHMrp42rxLf5e8a0aTJ48m3P3H3G-UM64p0puAPhmAwoB-MF2TrpiWQAWhxQEr0Ek2eDGxDxVUdk5WE4M7j7YGHXxECvHaJM7v0X9NbLrg_Ov22PofhauxoCf4Ap2rrFBKSFYKlSsmSwojaH4QmeByn0tWsFKVcqbw7VxiskxytpeFLDg_5EIJvtLe1uGycP4BBGhjrA?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNpNj0FLxDAQhf9KnJuQLcmmTbo57CIIiuBpb9JLaGdtoU12Y4LW0v9u2io4p8fMe9_MTFC7BkHDB94i2hofO_PuzVBZkuqh72rcHY8vrrWaPGPfO7JoSlr3SYxHMrp42rxLf5e8a0aTJ48m3P3H3G-UM64p0puAPhmAwoB-MF2TrpiWQAWhxQEr0Ek2eDGxDxVUdk5WE4M7j7YGHXxECvHaJM7v0X9NbLrg_Ov22PofhauxoCf4Ap2rrFBKSFYKlSsmSwojaH4QmeByn0tWsFKVcqbw7VxiskxytpeFLDg_5EIJvtLe1uGycP4BBGhjrA)

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## 🛠 Built With <a name="built-with"></a>

### Tech Stack <a name="tech-stack"></a>

> Describe the tech stack and include only the relevant sections that apply to your project.



<details>
  <summary>Server</summary>
  <ul>
    <li><a href="https://....">Name link</a></li>
  </ul>
</details>

<details>
<summary>Data store</summary>
  <ul>
   <li><a href="https://....">Name link</a></li>
  </ul>
</details>






### Key Features <a name="key-features"></a>

> Describe between 1-n* key features of the application.

- **[key_feature_1]**
- **[key_feature_2]**
- **[key_feature_3]**

<p align="right">(<a href="#readme-top">back to top</a>)</p>



## 🚀 Live Docs <a name="live-demo"></a>

> Add a link to your deployed project.

- [Live Docs Link](https://.....)

<p align="right">(<a href="#readme-top">back to top</a>)</p>



## 💻 Getting Started <a name="getting-started"></a>

> Describe how a new developer could make use of your project.

To get a local copy up and running, follow these steps.

### Prerequisites

In order to run this project you need:


Example command:

```sh
npm i -g x
```


### Setup

Clone this repository to your desired folder:


Example commands:

```sh
  git clone git@github.com:myaccount/my-project.git
  cd my-folder
```


### Install

Install this project with:


Example command:

```sh
  cd my-project

```


### Usage

To run the project, execute the following command:


Example command:

```sh

```


### Run tests

To run tests, run the following command:


Example command:

```sh

```


### Deployment

You can deploy this project using:


Example:

```sh

```


<p align="right">(<a href="#readme-top">back to top</a>)</p>



## 👥 Authors <a name="authors"></a>

> Mention all of the collaborators of this project.

👤 

- GitHub: [@githubhandle](https://github.com/githubhandle)
- GitHub: [@githubhandle](https://github.com/githubhandle)

<p align="right">(<a href="#readme-top">back to top</a>)</p>





## 🤝 Contributing <a name="contributing"></a>

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).

<p align="right">(<a href="#readme-top">back to top</a>)</p>



## ⭐️ Show your support <a name="support"></a>

> Write a message to encourage readers to support our project

If you like this project...join the zoom calls or loom at the label for `good-first-issue`

<p align="right">(<a href="#readme-top">back to top</a>)</p>



## 🙏 Acknowledgments <a name="acknowledgements"></a>

> Give credit to everyone who inspired our codebase.

I would like to thank...

<p align="right">(<a href="#readme-top">back to top</a>)</p>



## ❓ FAQ (OPTIONAL) <a name="faq"></a>

> Add at least 2 questions new developers would ask when they decide to use your project.

- **[Question_1]**

  - [Answer_1]

- **[Question_2]**

  - [Answer_2]

<p align="right">(<a href="#readme-top">back to top</a>)</p>



## 📝 License <a name="license"></a>

This project is [MIT](./LICENSE) licensed.

_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish._

<p align="right">(<a href="#readme-top">back to top</a>)</p>

**Comment by p5150j** [comment]
we could always add badges too I guess..

https://github.com/Ileriayo/markdown-badges

**Comment by JoeCap08055** [comment]
Looks great... let's make this into a PR that we keep open. I'll start with this as a template for one of the services, and we can incorporate any tweaks from that exercise back into this template.

**Comment by wilwade** [comment]
- Skip contributors
- Don't use the Frequency logo
- Our stuff is Apache 2.0 licensed

**Comment by p5150j** [comment]
send @wilwade the MD, he will edit and open a draft PR
