### ISSUE TITLE
[Publisher] Use mortal era of TX for crawling

### ISSUE THREAD

**Issue by saraswatpuneet** [AmplicaLabs/gateway#281]
## Details

- [ ] Instead of a constant for crawling blocks to find submitted tx, we may want to use mortal era from tx to decide how many blocks till a tx is valid, this will prevent CP to crawl many blocks.
- [ ] Move crawling function to blockchain package for generic use 

Current the constant is set to 32 blocks which is inline with default tx mortality of 32 blocks

**Comment by wilwade** [comment]
Replaced with #316
