### ISSUE TITLE
[account] Endpoints should not return SCALE-encoded values

### ISSUE THREAD

**Issue by JoeCap08055** [AmplicaLabs/gateway#304]
# Description
As a web2 developer, I want REST endpoints to return data in a standard, familiar format (ie, standard JSON types and objects). Currently, at least one endpoint in the `account-service` (`GET /accounts/:msaId`) returns the raw SCALE-encoded data that it gets back from the blockchain query (`handle` object contains SCALE-encoded `Text` and `u16` data). All SCALE-encoded data should be decoded by a Gateway service before returning to a client API.

**Comment by wilwade** [comment]
Related to https://github.com/AmplicaLabs/gateway/issues/303

**Comment by JoeCap08055** [comment]
Fixed by #312
